config/routes.rb
ClinicApp::Application.routes.draw do

  resources :appointments

  resources :doctors

  resources :patients
  resources :sessions
  resources :schedules  
  root :to => 'pages#home'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/privacy', :to => 'pages#privacy'
  match '/signup', :to => 'patients#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :date_of_birth, :first_name, :gender, :health_id, :last_name, :phone
  
  has_secure_password
  before_save :format_phone
  has_many :appointments
  has_many :doctors ,:through => :appointments
  
  validates_presence_of :password, :on => :create
  validates :email, :date_of_birth, :first_name, :gender, :health_id, :last_name, :phone, :presence => true
  validates_format_of :email, :with => /^[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info|qa))$/i, :message => "is not a valid form for an email-address"
  validates_format_of :phone, :with => /^(\+?\d{11}|\+?\d{3}?[-.]\d{4}[-.]\d{4})$/, :message => "should be 11 digits (country code needed) and delimited with appropiate symbols"

  Gender_List = [['Male'], ['Female']]

  scope :alphabetical, order('last_name, first_name')

  def proper_name
  	first_name + " " + last_name
  end	

  def name 
	last_name + ", " + first_name  	
  end

  private
  
    def format_phone
    phone = self.phone.to_s
    phone.gsub!(/[^0-9]/,"")
    self.phone = phone
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    @title = "Patient Directory"
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @title = "Patient Created"
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @title = "Sign up"
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @title = "Edit Details"
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
       # session[:patient_id] = patient.id
        format.html { redirect_to @patient, :notice => "Signed up!"}
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :health_id %><br />
    <%= f.number_field :health_id %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select(:gender, Patient::Gender_List) %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <tr>
    <th>Health</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Date of birth</th>
    <th>Gender</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= patient.health_id %></td>
    <td><%= patient.first_name %></td>
    <td><%= patient.last_name %></td>
    <td><%= patient.date_of_birth %></td>
    <td><%= patient.gender %></td>
    <td><%= patient.phone %></td>
    <td><%= patient.email %></td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Health:</b>
  <%= @patient.health_id %>
</p>

<p>
  <b>First name:</b>
  <%= @patient.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @patient.last_name %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @patient.date_of_birth %>
</p>

<p>
  <b>Gender:</b>
  <%= @patient.gender %>
</p>

<p>
  <b>Phone:</b>
  <%= @patient.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @patient.email %>
</p>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', root_path %>