config/routes.rb
ClinicApp::Application.routes.draw do

  resources :appointments

  resources :doctors

  resources :patients
  resources :sessions
  resources :schedules  
  root :to => 'pages#home'

  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/privacy', :to => 'pages#privacy'
  match '/signup', :to => 'patients#new'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :date, :doctor_id, :patient_id, :time_slot
  before_save :available
  validates :date, :doctor_id, :patient_id, :time_slot, :presence => true
  belongs_to :doctor
  belongs_to :patient

  SLOTS = [['8 am - 9 am'], ['9 am - 10 am'], ['10 am - 11 am'], ['11 am - 12 pm'], ['12 pm - 1 pm']]

  scope :chronological, order('date DESC')
  scope :latest, lambda{|num| limit(num).order('visit_date DESC')}

  private

  	def available
  		appointments_list = Appointment.all.map{|appointment| appointment}
	  	appointments_list.each do|appointment|
	  		date = appointment.date.to_default_s
        date_now = self.date.to_default_s
	  		if date == date_now && appointment.time_slot == self.time_slot
          errors.add(:appointment, "is not available")
	      	return false
	  		end
	  		return true 
		  end
	 end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json
  def index
    @title = "Appointments"
    @appointments = Appointment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @appointments }
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
     @title = "Show Appointment"
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
    @title = "New Appointment"
    @appointment = current_patient.appointments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @title = "Edit Appointment"
    @appointment = Appointment.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(params[:appointment])

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = Appointment.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br />
    <%= f.number_field :patient_id %>
  </div>

  <div class="field">
    <%= f.label :doctor_id %><br />
    <%= collection_select(:appointment, :doctor_id, Doctor.all, :id, :proper_name) %>
  </div>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time_slot %><br />
    <%= f.select(:time_slot, Appointment::SLOTS) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <tr>
    <th>Patient</th>
    <th>Doctor</th>
    <th>Date</th>
    <th>Time slot</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.patient.proper_name %></td>
    <td><%= appointment.doctor.proper_name %></td>
    <td><%= appointment.date %></td>
    <td><%= appointment.time_slot %></td>
    <td><%= link_to 'Show', appointment %></td>
    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
    <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Patient:</b>
  <%= @appointment.patient.proper_name %>
</p>

<p>
  <b>Doctor:</b>
  <%= @appointment.doctor.proper_name %>
</p>

<p>
  <b>Date:</b>
  <%= @appointment.date %>
</p>

<p>
  <b>Time slot:</b>
  <%= @appointment.time_slot %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>